N_TRIALS_TRAINING: 10
N_TRIALS_EXPERIMENT1: 25
N_TRIALS_EXPERIMENT2: 25
N_TRIALS_EXPERIMENT3: 25
TRIAL_TIME: 0.95
REACTION_KEYS: "right"
FIX_CROSS_COLOR: "red"
STIM_COLOR2: "white"
KEYS: ["space", "f7"]
